diff a/docs/Makefile b/docs/Makefile	(rejected hunks)
@@ -139,39 +139,82 @@
 	@echo "Run \`make' in that directory to run these through makeinfo" \
 	      "(use \`make info' here to do that automatically)."
 
+<<<<<<< HEAD
+=======
+.PHONY: info
+>>>>>>> pyup-update-asciimatics-1.6.0-to-1.7.0
 info:
 	$(SPHINXBUILD) -b texinfo $(ALLSPHINXOPTS) $(BUILDDIR)/texinfo
 	@echo "Running Texinfo files through makeinfo..."
 	make -C $(BUILDDIR)/texinfo info
 	@echo "makeinfo finished; the Info files are in $(BUILDDIR)/texinfo."
 
+<<<<<<< HEAD
+=======
+.PHONY: gettext
+>>>>>>> pyup-update-asciimatics-1.6.0-to-1.7.0
 gettext:
 	$(SPHINXBUILD) -b gettext $(I18NSPHINXOPTS) $(BUILDDIR)/locale
 	@echo
 	@echo "Build finished. The message catalogs are in $(BUILDDIR)/locale."
 
+<<<<<<< HEAD
+=======
+.PHONY: changes
+>>>>>>> pyup-update-asciimatics-1.6.0-to-1.7.0
 changes:
 	$(SPHINXBUILD) -b changes $(ALLSPHINXOPTS) $(BUILDDIR)/changes
 	@echo
 	@echo "The overview file is in $(BUILDDIR)/changes."
 
+<<<<<<< HEAD
+=======
+.PHONY: linkcheck
+>>>>>>> pyup-update-asciimatics-1.6.0-to-1.7.0
 linkcheck:
 	$(SPHINXBUILD) -b linkcheck $(ALLSPHINXOPTS) $(BUILDDIR)/linkcheck
 	@echo
 	@echo "Link check complete; look for any errors in the above output " \
 	      "or in $(BUILDDIR)/linkcheck/output.txt."
 
+<<<<<<< HEAD
+=======
+.PHONY: doctest
+>>>>>>> pyup-update-asciimatics-1.6.0-to-1.7.0
 doctest:
 	$(SPHINXBUILD) -b doctest $(ALLSPHINXOPTS) $(BUILDDIR)/doctest
 	@echo "Testing of doctests in the sources finished, look at the " \
 	      "results in $(BUILDDIR)/doctest/output.txt."
 
+<<<<<<< HEAD
+=======
+.PHONY: coverage
+coverage:
+	$(SPHINXBUILD) -b coverage $(ALLSPHINXOPTS) $(BUILDDIR)/coverage
+	@echo "Testing of coverage in the sources finished, look at the " \
+	      "results in $(BUILDDIR)/coverage/python.txt."
+
+.PHONY: xml
+>>>>>>> pyup-update-asciimatics-1.6.0-to-1.7.0
 xml:
 	$(SPHINXBUILD) -b xml $(ALLSPHINXOPTS) $(BUILDDIR)/xml
 	@echo
 	@echo "Build finished. The XML files are in $(BUILDDIR)/xml."
 
+<<<<<<< HEAD
+=======
+.PHONY: pseudoxml
+>>>>>>> pyup-update-asciimatics-1.6.0-to-1.7.0
 pseudoxml:
 	$(SPHINXBUILD) -b pseudoxml $(ALLSPHINXOPTS) $(BUILDDIR)/pseudoxml
 	@echo
 	@echo "Build finished. The pseudo-XML files are in $(BUILDDIR)/pseudoxml."
+<<<<<<< HEAD
+=======
+
+.PHONY: dummy
+dummy:
+	$(SPHINXBUILD) -b dummy $(ALLSPHINXOPTS) $(BUILDDIR)/dummy
+	@echo
+	@echo "Build finished. Dummy builder generates no files."
+>>>>>>> pyup-update-asciimatics-1.6.0-to-1.7.0
